export const ErrorCodes = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  TOKEN_VERSION_MISMATCH: 'TOKEN_VERSION_MISMATCH',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // Lecture
  LECTURE_NOT_FOUND: 'LECTURE_NOT_FOUND',
  INVALID_LECTURE_ORDER: 'INVALID_LECTURE_ORDER',

  // Assignment
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  ALREADY_SUBMITTED: 'ALREADY_SUBMITTED',
  DEADLINE_PASSED: 'DEADLINE_PASSED',

  // Payment
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // File Upload
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Route
  NOT_FOUND: 'NOT_FOUND',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
