export enum Subject {
  ARABIC = 'Arabic',
  MATH = 'Mathematics',
  SCIENCE = 'Science',
  ENGLISH = 'English',
  HISTORY = 'History',
  STATISTICS = 'Statistics',
  PROGRAMMING = 'Programming',
  BIOLOGY = 'Biology',
  CHEMISTRY = 'Chemistry',
  PHYSICS = 'Physics',
  GEOGRAPHY = 'Geography',
  PSYCHOLOGY = 'Psychology',
  PHILOSOPHY = 'Philosophy',
  STATICS = 'Statics',
  DYNAMICS = 'Dynamics',
  ALGEBRA = 'Algebra',
  GEOMETRY = 'Geometry',
  TRIGONOMETRY = 'Trigonometry',
  FRENSH = 'French',
  SPANISH = 'Spanish',
  GERMAN = 'German',
  ITALIAN = 'Italian',
}